# Generated by Django 3.2.7 on 2021-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dogimage',
            field=models.ImageField(blank=True, null=True, upload_to='dogimages/'),
        ),
    ]
