# Generated by Django 2.2 on 2021-09-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_blog_app', '0002_auto_20210923_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_posts', to='dog_blog_app.User'),
        ),
    ]
