# Generated by Django 2.2 on 2021-09-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_blog_app', '0002_auto_20210923_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dogimage',
            field=models.ImageField(blank=True, default='none', null=True, upload_to='dogimages/'),
        ),
    ]
